export const Dairy = [
  {
    image: "mealplaceholder.jpg",
    type: "dairy",
    servings: 1,
    unit: "cup",
    name: "unsweetened nut milk",
    protein: 1,
    fat: 3,
    carbohydrates: 1,
    calories: 30,
  },
  {
    image: "mealplaceholder.jpg",
    type: "dairy",
    servings: 1,
    unit: "cup",
    name: "kefir",
    protein: 1,
    fat: 3,
    carbohydrates: 1,
    calories: 30,
  },
  {
    image: "mealplaceholder.jpg",
    type: "dairy",
    servings: 1,
    unit: "cup",
    name: "low fat cottage cheese",
    protein: 1,
    fat: 3,
    carbohydrates: 1,
    calories: 30,
  },
  {
    image: "mealplaceholder.jpg",
    type: "dairy",
    servings: 1,
    unit: "cup",
    name: "low fat milk",
    protein: 1,
    fat: 3,
    carbohydrates: 1,
    calories: 30,
  },
  {
    image: "mealplaceholder.jpg",
    type: "dairy",
    servings: 1,
    unit: "cup",
    name: "low fat plain greek yogurt",
    protein: 1,
    fat: 3,
    carbohydrates: 1,
    calories: 30,
  },
  {
    image: "mealplaceholder.jpg",
    type: "dairy",
    servings: 1,
    unit: "cup",
    name: "low fat plain yogurt",
    protein: 1,
    fat: 3,
    carbohydrates: 1,
    calories: 30,
  },
  {
    image: "mealplaceholder.jpg",
    type: "dairy",
    servings: 1,
    unit: "cup",
    name: "non fat cottage cheese",
    protein: 1,
    fat: 3,
    carbohydrates: 1,
    calories: 30,
  },
  {
    image: "mealplaceholder.jpg",
    type: "dairy",
    servings: 1,
    unit: "cup",
    name: "non fat plain greek yogurt",
    protein: 1,
    fat: 3,
    carbohydrates: 1,
    calories: 30,
  },
  {
    image: "mealplaceholder.jpg",
    type: "dairy",
    servings: 1,
    unit: "cup",
    name: "non fat plain yogurt",
    protein: 1,
    fat: 3,
    carbohydrates: 1,
    calories: 30,
  },
  {
    image: "mealplaceholder.jpg",
    type: "dairy",
    servings: 1,
    unit: "cup",
    name: "skim milk",
    protein: 1,
    fat: 3,
    carbohydrates: 1,
    calories: 30,
  },
  {
    image: "mealplaceholder.jpg",
    type: "dairy",
    servings: 1,
    unit: "oz",
    name: "low fat cheese",
    protein: 1,
    fat: 3,
    carbohydrates: 1,
    calories: 30,
  },
  {
    image: "mealplaceholder.jpg",
    type: "dairy",
    servings: 1,
    unit: "oz",
    name: "American Cheese (processed)",
    calories: 102,
    fat: 9,
    protien: 5,
  },
  {
    image: "mealplaceholder.jpg",
    type: "dairy",
    servings: 1,
    unit: "oz",
    name: "Blue Cheese",
    calories: 100,
    fat: 5,
    protein: 6,
  },
  {
    image: "mealplaceholder.jpg",
    type: "dairy",
    servings: 1,
    unit: "oz",
    name: "Brie",
    calories: 95,
    fat: 8,
    protein: 6,
  },
  {
    image: "mealplaceholder.jpg",
    type: "dairy",
    servings: 1,
    unit: "oz",
    name: "Brick",
    calories: 105,
    fat: 8,
    protein: 7,
  },
  {
    image: "mealplaceholder.jpg",
    type: "dairy",
    servings: 1,
    unit: "oz",
    name: "Camembert",
    calories: 85,
    fat: 7,
    protien: 6,
  },
  {
    image: "mealplaceholder.jpg",
    type: "dairy",
    servings: 1,
    unit: "oz",
    name: "Cheddar",
    calories: 115,
    fat: 9,
    protein: 6,
  },
  {
    image: "mealplaceholder.jpg",
    type: "dairy",
    servings: 1,
    unit: "oz",
    name: "Cottage (1% milkfat)",
    calories: 81,
    fat: 1,
    protein: 14,
  },
  {
    image: "mealplaceholder.jpg",
    type: "dairy",
    servings: 1,
    unit: "oz",
    name: "Cream Cheese",
    calories: 99,
    fat: 10,
    protein: 2,
  },
  {
    image: "mealplaceholder.jpg",
    type: "dairy",
    servings: 1,
    unit: "oz",
    name: "Feta",
    calories: 75,
    fat: 6,
    protein: 4,
  },
  {
    image: "mealplaceholder.jpg",
    type: "dairy",
    servings: 1,
    unit: "oz",
    name: "Goat Cheese (soft)",
    calories: 75,
    fat: 6,
    protein: 5,
  },
  {
    image: "mealplaceholder.jpg",
    type: "dairy",
    servings: 1,
    unit: "oz",
    name: "Gouda",
    calories: 101,
    fat: 8,
    protein: 7,
  },
  {
    image: "mealplaceholder.jpg",
    type: "dairy",
    servings: 1,
    unit: "oz",
    name: "Monterey Jack",
    calories: 106,
    fat: 9,
    protein: 7,
  },
  {
    image: "mealplaceholder.jpg",
    type: "dairy",
    servings: 1,
    unit: "oz",
    name: "Mozzarella (whole milk)",
    calories: 85,
    fat: 6,
    protein: 6,
  },
  {
    image: "mealplaceholder.jpg",
    type: "dairy",
    servings: 1,
    unit: "oz",
    name: "Mozzarella (skim milk)",
    calories: 84,
    fat: 6,
    protein: 7,
  },
  {
    image: "mealplaceholder.jpg",
    type: "dairy",
    servings: 1,
    unit: "oz",
    name: "Muenster",
    calories: 104,
    fat: 9,
    protein: 7,
  },
  {
    image: "mealplaceholder.jpg",
    type: "dairy",
    servings: 1,
    unit: "oz",
    name: "Parmesan",
    calories: 111,
    fat: 7,
    protein: 10,
  },
  {
    image: "mealplaceholder.jpg",
    type: "dairy",
    servings: 1,
    unit: "oz",
    name: "Provolone",
    calories: 100,
    fat: 8,
    protein: 7,
  },
  {
    image: "mealplaceholder.jpg",
    type: "dairy",
    servings: 1,
    unit: "oz",
    name: "String Cheese",
    calories: 80,
    fat: 6,
    protein: 7,
  },
  {
    image: "mealplaceholder.jpg",
    type: "dairy",
    servings: 1,
    unit: "oz",
    name: "Swiss",
    calories: 111,
    fat: 9,
    protien: 8,
  },
];
