export const Fruit = [
  {
    image: "mealplaceholder.jpg",
    type: "fruit",
    servings: 1,
    unit: "small",
    name: "apples",
    protein: 0.2,
    fat: 0.3,
    carbohydrates: 20,
    calories: 72,
  },
  {
    image: "mealplaceholder.jpg",
    type: "fruit",
    servings: 3,
    unit: "medium",
    name: "apricots",
    protein: 1,
    fat: 0,
    carbohydrates: 22,
    calories: 90,
  },
  {
    image: "mealplaceholder.jpg",
    type: "fruit",
    servings: 0.5,
    unit: "medium",
    name: "avocado",
    protein: 2,
    fat: 10,
    carbohydrates: 6,
    calories: 120,
  },
  {
    image: "mealplaceholder.jpg",
    type: "fruit",
    servings: 1,
    unit: "medium",
    name: "bananas",
    protein: 1,
    fat: 0,
    carbohydrates: 27,
    calories: 105,
  },
  {
    image: "mealplaceholder.jpg",
    type: "fruit",
    servings: 1,
    unit: "cup",
    name: "blackberries",
    protein: 1,
    fat: 0,
    carbohydrates: 10,
    calories: 43,
  },
  {
    image: "mealplaceholder.jpg",
    type: "fruit",
    servings: 1,
    unit: "cup",
    name: "blueberries",
    protein: 1,
    fat: 0,
    carbohydrates: 14,
    calories: 57,
  },
  {
    image: "mealplaceholder.jpg",
    type: "fruit",
    servings: 1,
    unit: "cup",
    name: "boysenberries",
    protein: 1,
    fat: 0,
    carbohydrates: 12,
    calories: 50,
  },
  {
    image: "mealplaceholder.jpg",
    type: "fruit",
    servings: 1,
    unit: "cup",
    name: "cherries",
    protein: 1,
    fat: 0,
    carbohydrates: 12,
    calories: 50,
  },
  {
    image: "mealplaceholder.jpg",
    type: "fruit",
    servings: 1,
    unit: "small",
    name: "clementines",
    protein: 1,
    fat: 0,
    carbohydrates: 12,
    calories: 47,
  },
  {
    image: "mealplaceholder.jpg",
    type: "fruit",
    servings: 1,
    unit: "cup",
    name: "cranberries",
    protein: 0,
    fat: 0,
    carbohydrates: 12,
    calories: 46,
  },
  {
    image: "mealplaceholder.jpg",
    type: "fruit",
    servings: 10,
    unit: "small",
    name: "dates",
    protein: 0.5,
    fat: 0,
    carbohydrates: 18,
    calories: 66,
  },
  {
    image: "mealplaceholder.jpg",
    type: "fruit",
    servings: 5,
    unit: "small",
    name: "figs",
    protein: 1,
    fat: 0,
    carbohydrates: 19,
    calories: 74,
  },
  {
    image: "mealplaceholder.jpg",
    type: "fruit",
    servings: 1,
    unit: "tbsp",
    name: "goji berries, dried",
    protein: 5,
    fat: 0,
    carbohydrates: 13,
    calories: 70,
  },
  {
    image: "mealplaceholder.jpg",
    type: "fruit",
    servings: 1,
    unit: "medium ",
    name: "grapefruit",
    protein: 10.5,
    fat: 0,
    carbohydrates: 21,
    calories: 82,
  },
  {
    image: "mealplaceholder.jpg",
    type: "fruit",
    servings: 1,
    unit: "cup",
    name: "grapes, red or green",
    protein: 1,
    fat: 0,
    carbohydrates: 18,
    calories: 69,
  },
  {
    image: "mealplaceholder.jpg",
    type: "fruit",
    servings: 1,
    unit: "cup",
    name: "guavas",
    protein: 3,
    fat: 1,
    carbohydrates: 14,
    calories: 68,
  },
  {
    image: "mealplaceholder.jpg",
    type: "fruit",
    servings: 1,
    unit: "medium",
    name: "lemon",
    protein: 0.64,
    fat: 0.17,
    carbohydrates: 5.41,
    calories: 17,
  },
  {
    image: "mealplaceholder.jpg",
    type: "fruit",
    servings: 1,
    unit: "medium",
    name: "limes",
    protein: 1,
    fat: 0,
    carbohydrates: 11,
    calories: 30,
  },
  {
    image: "mealplaceholder.jpg",
    type: "fruit",
    servings: 1,
    unit: "cup ",
    name: "mangos",
    protein: 1,
    fat: 0,
    carbohydrates: 15,
    calories: 60,
  },
  {
    image: "mealplaceholder.jpg",
    type: "fruit",
    servings: 1,
    unit: "cup",
    name: "melons, cantaloupe",
    protein: 1,
    fat: 0,
    carbohydrates: 8,
    calories: 34,
  },
  {
    image: "mealplaceholder.jpg",
    type: "fruit",
    servings: 1,
    unit: "cup",
    name: "melons, casaba",
    protein: 1,
    fat: 0,
    carbohydrates: 7,
    calories: 28,
  },
  {
    image: "mealplaceholder.jpg",
    type: "fruit",
    servings: 1,
    unit: "cup",
    name: "melons, honeydew",
    protein: 1,
    fat: 0,
    carbohydrates: 9,
    calories: 36,
  },
  {
    image: "mealplaceholder.jpg",
    type: "fruit",
    servings: 1,
    unit: "medium",
    name: "nectarines",
    protein: 1,
    fat: 0,
    carbohydrates: 14,
    calories: 60,
  },
  {
    image: "mealplaceholder.jpg",
    type: "fruit",
    servings: 1,
    unit: "medium",
    name: "orange",
    protein: 1,
    fat: 0,
    carbohydrates: 15,
    calories: 62,
  },
  {
    image: "mealplaceholder.jpg",
    type: "fruit",
    servings: 1,
    unit: "cup ",
    name: "papayas",
    protein: 0,
    fat: 0,
    carbohydrates: 11,
    calories: 43,
  },
  {
    image: "mealplaceholder.jpg",
    type: "fruit",
    servings: 1,
    unit: "cup",
    name: "passion-fruit",
    protein: 2,
    fat: 1,
    carbohydrates: 23,
    calories: 97,
  },
  {
    image: "mealplaceholder.jpg",
    type: "fruit",
    servings: 1,
    unit: "medium",
    name: "pear",
    protein: 0,
    fat: 0,
    carbohydrates: 25,
    calories: 96,
  },
  {
    image: "mealplaceholder.jpg",
    type: "fruit",
    servings: 1,
    unit: "cup",
    name: "pineapple",
    protein: 1,
    fat: 0,
    carbohydrates: 14,
    calories: 51,
  },
  {
    image: "mealplaceholder.jpg",
    type: "fruit",
    servings: 1,
    unit: "cup",
    name: "plantains",
    protein: 1,
    fat: 0,
    carbohydrates: 32,
    calories: 122,
  },
  {
    image: "mealplaceholder.jpg",
    type: "fruit",
    servings: 1,
    unit: "cup",
    name: "plums",
    protein: 1,
    fat: 0,
    carbohydrates: 11,
    calories: 46,
  },
  {
    image: "mealplaceholder.jpg",
    type: "fruit",
    servings: 1,
    unit: "cup",
    name: "pomegranates",
    protein: 2,
    fat: 1,
    carbohydrates: 19,
    calories: 83,
  },
  {
    image: "mealplaceholder.jpg",
    type: "fruit",
    servings: 1,
    unit: "cup",
    name: "raspberries",
    protein: 1,
    fat: 1,
    carbohydrates: 12,
    calories: 52,
  },
  {
    image: "mealplaceholder.jpg",
    type: "fruit",
    servings: 1,
    unit: "cup",
    name: "rhubarb",
    protein: 1,
    fat: 0,
    carbohydrates: 5,
    calories: 21,
  },
  {
    image: "mealplaceholder.jpg",
    type: "fruit",
    servings: 1,
    unit: "cup",
    name: "strawberries",
    protein: 1,
    fat: 0,
    carbohydrates: 11,
    calories: 46,
  },
  {
    image: "mealplaceholder.jpg",
    type: "fruit",
    servings: 1,
    unit: "small",
    name: "tangerines",
    protein: 0.5,
    fat: 0,
    carbohydrates: 9,
    calories: 37,
  },
  {
    image: "mealplaceholder.jpg",
    type: "fruit",
    servings: 1,
    unit: "cup",
    name: "watermelon",
    protein: 1,
    fat: 0,
    carbohydrates: 8,
    calories: 30,
  },
];
