export const Starch = [
  {
    image: "mealplaceholder.jpg",
    type: "grains & starch",
    servings: 1,
    unit: "cup",
    name: "brown rice, cooked",
    protein: 0,
    fat: 13.5,
    carbohydrates: 0,
    calories: 119,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "cup",
    name: "white potato",
    protein: 3,
    fat: 0,
    carbohydrates: 22,
    calories: 104,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "medium",
    name: "red potato",
    protein: 4.03,
    fat: 0.3,
    carbohydrates: 33.87,
    calories: 153,
  },

  {
    image: "mealplaceholder.jpg",
    type: "grains & starch",
    servings: 1,
    unit: "cup",
    name: "white rice, cooked",
    protein: 0,
    fat: 13.5,
    carbohydrates: 0,
    calories: 119,
  },
  {
    image: "mealplaceholder.jpg",
    type: "grains & starch",
    servings: 1,
    unit: "cup",
    name: "beans and lentils, cooked",
    protein: 0,
    fat: 13.5,
    carbohydrates: 0,
    calories: 119,
  },
  {
    image: "mealplaceholder.jpg",
    type: "grains & starch",
    servings: 0.5, //48g,
    unit: "cup",
    servingsIngrams: 48,
    name: "old fashioned rolled oats",
    protein: 7,
    fat: 3.5,
    carbohydrates: 32,
    calories: 190,
  },
  {
    image: "mealplaceholder.jpg",
    type: "grains & starch",
    servings: 0.5,
    unit: "cup",
    name: "steal cut oats",
    protein: 0,
    fat: 13.5,
    carbohydrates: 0,
    calories: 119,
  },
];
