export const Veggies = [
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "cup",
    name: "artichokes",
    protein: 2,
    fat: 0,
    carbohydrates: 17,
    calories: 73,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "cup",
    name: "arugula",
    protein: 3,
    fat: 1,
    carbohydrates: 4,
    calories: 25,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "cup",
    name: "asparagus",
    protein: 2,
    fat: 0,
    carbohydrates: 4,
    calories: 20,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "medium",
    name: "bell pepper",
    protein: 1.18,
    fat: 0.36,
    carbohydrates: 7.18,
    calories: 31,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "cup",
    name: "broccoli",
    protein: 3,
    fat: 0,
    carbohydrates: 5,
    calories: 28,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "cup",
    name: "brussel sprouts",
    protein: 3,
    fat: 1,
    carbohydrates: 8,
    calories: 38,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "cup",
    name: "butterhead lettuce",
    protein: 1,
    fat: 0,
    carbohydrates: 2,
    calories: 13,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "cup",
    name: "butternut squash",
    protein: 1,
    fat: 0,
    carbohydrates: 16,
    calories: 63,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "cup",
    name: "cabbage",
    protein: 2,
    fat: 0,
    carbohydrates: 2,
    calories: 13,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "can",
    name: "canned diced tomatoes",
    protein: 3.5,
    fat: 0,
    carbohydrates: 17.5,
    calories: 87.5,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "cup",
    name: "carrots",
    protein: 1,
    fat: 0,
    carbohydrates: 10,
    calories: 41,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "cup ",
    name: "cauliflower",
    protein: 2,
    fat: 0,
    carbohydrates: 5,
    calories: 25,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "cup",
    name: "celery",
    protein: 1,
    fat: 0,
    carbohydrates: 3,
    calories: 16,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "cup",
    name: "cherry tomatoes",
    protein: 1,
    fat: 0,
    carbohydrates: 6,
    calories: 27,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 0.5,
    unit: "cup",
    name: "cilantro",
    protein: 4,
    fat: 2,
    carbohydrates: 8,
    calories: 46,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "cup",
    name: "cooked beets",
    protein: 2.6,
    fat: 3.6,
    carbohydrates: 15.7,
    calories: 99,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "cup",
    name: "cucumber",
    protein: 1,
    fat: 0,
    carbohydrates: 2,
    calories: 12,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "cup",
    name: "eggplant",
    protein: 0.83,
    fat: 0.16,
    carbohydrates: 4.6,
    calories: 20,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 0.5,
    unit: "cup",
    name: "endive",
    protein: 1,
    fat: 0,
    carbohydrates: 3,
    calories: 17,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "cup",
    name: "green beans",
    protein: 2,
    fat: 0,
    carbohydrates: 7,
    calories: 31,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "cup",
    name: "green leaf lettuce",
    protein: 1,
    fat: 0,
    carbohydrates: 3,
    calories: 15,
  },
  {
    _id: "5d9bd85519a26f739df755b7",
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "cup",
    name: "green peas",
    protein: 5,
    fat: 0,
    carbohydrates: 14,
    calories: 81,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "",
    name: "jalapeno pepper",
    protein: 0.19,
    fat: 0,
    carbohydrates: 0.83,
    calories: 4,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "cup",
    name: "kale",
    protein: 3,
    fat: 1,
    carbohydrates: 8,
    calories: 42,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "cup",
    name: "mushrooms",
    protein: 2.16,
    fat: 0.24,
    carbohydrates: 2.3,
    calories: 15,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "cup",
    name: "okra",
    protein: 2,
    fat: 0,
    carbohydrates: 7,
    calories: 33,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "cup",
    name: "onions",
    protein: 2,
    fat: 0,
    carbohydrates: 7,
    calories: 32,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "cup",
    name: "parsley",
    protein: 1.78,
    fat: 0.47,
    carbohydrates: 3.8,
    calories: 22,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "cup",
    name: "radicchio",
    protein: 1,
    fat: 0,
    carbohydrates: 4,
    calories: 23,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "cup",
    name: "radishes",
    protein: 1,
    fat: 0,
    carbohydrates: 3,
    calories: 16,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "medium",
    name: "red onion",
    protein: 1.01,
    fat: 0.09,
    carbohydrates: 11.12,
    calories: 46,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "cup",
    name: "romaine lettuce",
    protein: 1,
    fat: 0,
    carbohydrates: 3,
    calories: 17,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "tbsp ",
    name: "shallots",
    protein: 3,
    fat: 0,
    carbohydrates: 17,
    calories: 72,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "cup",
    name: "snap beans",
    protein: 2,
    fat: 0,
    carbohydrates: 7,
    calories: 31,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 2,
    unit: "cup",
    name: "spaghetti squash",
    protein: 2,
    fat: 2,
    carbohydrates: 20,
    calories: 84,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "cup",
    name: "spinach",
    protein: 2,
    fat: 0,
    carbohydrates: 4,
    calories: 22,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "cup",
    name: "spring mix",
    protein: 1,
    fat: 0,
    carbohydrates: 4,
    calories: 15,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "cup",
    name: "summer squash",
    protein: 1,
    fat: 0,
    carbohydrates: 3,
    calories: 16,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "cup",
    name: "sweet potato",
    protein: 2,
    fat: 0,
    carbohydrates: 27,
    calories: 114,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "cup",
    name: "swiss chard",
    protein: 2,
    fat: 0,
    carbohydrates: 4,
    calories: 19,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "medium",
    name: "tomatoes",
    protein: 1,
    fat: 0,
    carbohydrates: 5,
    calories: 22,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "cup",
    name: "turnips",
    protein: 1,
    fat: 0,
    carbohydrates: 6,
    calories: 28,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "cup",
    name: "yam",
    protein: 2,
    fat: 0,
    carbohydrates: 28,
    calories: 118,
  },
  {
    image: "mealplaceholder.jpg",
    type: "vegetables",
    servings: 1,
    unit: "medium",
    name: "zucchini",
    protein: 2,
    fat: 0,
    carbohydrates: 7,
    calories: 31,
  },
];
